### PR TITLE
Fix compile issue on later ESPHome (fixes #2)

### LINKED ISSUE #2: Fails to compile on ESPHome 2022.12.3  (fix included)
I only found this because I noticed the copy of HomeAssistant on my Home Assistant on my local instance was stuck at version 2022.3.1. The version in the Add-ons Store was 2022.12.x but had moved repository -- I had to uninstall it, then reinstall it from the store to make it update.

After updating, the Flipdot driver failed to build with this error:

```
Compiling /data/flipdot-small/.pioenvs/flipdot-small/lib64d/WiFi/WiFiClient.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:253:51: error: invalid new-expression of abstract class type 'esphome::hanover_flipdot::hanover_flipdot'
   flipdot1 = new hanover_flipdot::hanover_flipdot();
                                                   ^
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/hanover_flipdot/hanover_flipdot.h:10:7: note:   because the following virtual functions are pure within 'esphome::hanover_flipdot::hanover_flipdot':
 class hanover_flipdot : public PollingComponent, public display::DisplayBuffer, public uart::UARTDevice  {
       ^~~~~~~~~~~~~~~
In file included from src/esphome.h:16,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:375:23: note: 	'virtual esphome::display::DisplayType esphome::display::DisplayBuffer::get_display_type()'
   virtual DisplayType get_display_type() = 0;
                       ^~~~~~~~~~~~~~~~
Compiling /data/flipdot-small/.pioenvs/flipdot-small/lib64d/WiFi/WiFiGeneric.cpp.o
*** [/data/flipdot-small/.pioenvs/flipdot-small/src/main.cpp.o] Error 1
```

This seems to be due to an API change in the ESPHome display component. Adding this line to the `public` section of the `hanover_flipdot` class (above the `protected:` block) in `hanover_flipdot.h` fixes it:

```
  display::DisplayType get_display_type() override { return  display::DisplayType::DISPLAY_TYPE_BINARY; }
```

### PR DESCRIPTION
**Pull request by philpem**
Implement the "get_display_type()" method, which is required by later ESPHome releases.

### CODE REVIEW

**Comment by philpem** [comment]
Updated this PR to also account for changes needed on ESPHome 2023.12.0

Merry Christmas!
